package com.hnguyen703.tp3observability.analysis;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class LogAnalyzer {

    public static void main(String[] args) {
        String logFile = "application.json"; // The file generated by Spring Boot
        Map<String, UserProfileBuilder> builders = new HashMap<>();
        Gson gson = new Gson();

        System.out.println("--- ANALYZING USER PROFILES ---");

        try (BufferedReader br = new BufferedReader(new FileReader(logFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Only take the lines that are actual JSON logs we injected
                if (!line.contains("{") || !line.contains("\"user\":")) continue;

                // Extract the JSON part from the log line (skip Spring's standard prefixes)
                String jsonPart = line.substring(line.indexOf("{"));

                try {
                    JsonObject logEntry = gson.fromJson(jsonPart, JsonObject.class);

                    if (logEntry.has("user") && logEntry.has("type")) {
                        String userId = logEntry.get("user").getAsString();
                        String type = logEntry.get("type").getAsString();

                        // Create the Builder for this user
                        builders.putIfAbsent(userId, new UserProfileBuilder(userId));
                        UserProfileBuilder builder = builders.get(userId);

                        // Update stats
                        if ("READ".equals(type)) {
                            builder.incrementReads();
                        } else if ("WRITE".equals(type)) {
                            builder.incrementWrites();
                        }
                    }
                } catch (Exception e) {
                    // Ignore lines that aren't valid JSON (e.g. Spring startup logs)
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading log file: " + e.getMessage());
            return;
        }

        // Build and Print Profiles
        for (UserProfileBuilder builder : builders.values()) {
            System.out.println(builder.build());
        }
    }

    // --- Helper Classes following Builder Pattern ---

    static class UserProfile {
        String userId;
        int readCount;
        int writeCount;
        String profileType;

        @Override
        public String toString() {
            return String.format("User: %-15s | Reads: %-3d | Writes: %-3d | Profile: %s",
                    userId, readCount, writeCount, profileType);
        }
    }

    static class UserProfileBuilder {
        private final String userId;
        private int readCount = 0;
        private int writeCount = 0;

        public UserProfileBuilder(String userId) {
            this.userId = userId;
        }

        public void incrementReads() { this.readCount++; }
        public void incrementWrites() { this.writeCount++; }

        public UserProfile build() {
            UserProfile profile = new UserProfile();
            profile.userId = this.userId;
            profile.readCount = this.readCount;
            profile.writeCount = this.writeCount;

            // Logic to determine profile type
            if (readCount > writeCount * 2) {
                profile.profileType = "HEAVY READER";
            } else if (writeCount > readCount * 2) {
                profile.profileType = "HEAVY WRITER";
            } else {
                profile.profileType = "REGULAR / BALANCED";
            }
            return profile;
        }
    }
}